version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - target: 3000
        published: 3000
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://db:27017/methcodus
      ALLOWED_ORIGIN: '*'
      PORT: 3000
      PAIR_PROGRAMMING_REQUESTS_MAX_AGE: 300000
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: npm run start:dev
  db:
    image: mongo:3.6.9
    ports:
      - target: 27017
        published: 27017
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
volumes:
  mongo-data:
networks:
  default:
    name: methcodus
